### ISSUE TITLE
gtk.GtkWarning: could not open display

### ISSUE THREAD

**Issue by sergioymar** [pavelyazev/gr-dect2#9]
Hello everyone, I made the installation from the bash console in windows 10 using ubuntu 16.04 following the instructions and when opening the gnuradio-companion file I get the following errors:

Traceback (most recent call last):
File "/usr/local/bin/gnuradio-companion", line 97, in <module>
check_gtk()
File "/usr/local/bin/gnuradio-companion", line 64, in check_gtk
die(err, "Failed to initialize GTK. If you are running over ssh, "
File "/usr/local/bin/gnuradio-companion", line 42, in die
import gtk
File "/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py", line 69, in <module>
_init()
File "/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py", line 57, in _init
warnings.warn(str(e), _gtk.Warning)
gtk.GtkWarning: could not open display

Could someone tell me how to fix this error? 

Thank you very much in advance and a very cordial greeting for all.

**Comment by ixn872** [comment]
same issue...
